[package]
name = "embedded-async"
version = "0.1.0"
authors = ["Andreas Wass <wass.andreas@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
smol = "1.0.1"
pin-utils = "0.1.0"